### ISSUE TITLE
Package unavailable on npm/unpkg/skypack/…

### ISSUE THREAD

**Issue by bramus** [oddbird/popup-polyfill#30]
https://unpkg.com/browse/@oddbird/popup-polyfill/dist/ shows “cannot find package”
https://www.npmjs.com/package/@oddbird/popup-polyfill gives a 404
https://www.npmjs.com/search?q=%40oddbird%2Fpopup-polyfill shows no results

Has this package been removed?

**Comment by jgerigmeyer** [comment]
Fixed: https://www.npmjs.com/package/@oddbird/popup-polyfill
